version: '3.7'

services:
  react_demo:
    container_name: react_demo
    build: ./
    volumes:
      - './:/react_demo'
      - '/react_demo/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start