version: '3.7'

services:
  react_demo:
    container_name: ReactDemo
    build: 
      dockerfile: Dockerfile
      context: app/
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start